[project]
name = "pokemon-emerald"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arcade>=3.3.3",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "pyright>=1.1.409",
    "ruff>=0.15.7",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.bandit]
skips = ["B311"]
